project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

project/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name='Date Published')

    def __str__(self):
        return self.question_text

    def  was_published_recently(self):
        today = timezone.now()
        tomorrow = datetime.timedelta(days=1)
        return today - tomorrow <= self.pub_date <= today

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

project/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    context_object_name = 'questions'

    def get_queryset(self):
        today = timezone.now()
        return (
            Question
            .objects
            .filter(pub_date__lte=today)
            .order_by('-pub_date')

        )[:5]


class DetailView(generic.DetailView):
    model = Question

    def get_queryset(self):
        today = timezone.now()
        return Question.objects.filter(pub_date__lte=today)


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/question_results.html'


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        template = 'polls/question_detail.html'
        context = {
            'question': question,
            'error_message': 'You didn\'t select a choice.'
        }
        return render(request, template, context)
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

project/polls/templates/polls/base.html
{% extends "base.html" %}
{% load static %}

{% block title %}Polls App{% endblock %}

{% block head %}
<link href="{% static 'polls/css/polls.css' %}" rel="stylesheet" />
{% endblock %}

{% block main %}
<div class="app-image">
    <img alt="" src="{% static 'polls/img/polls.png' %}" />
</div>
{% endblock %}

{% block foot %}
<script src="{% static 'polls/js/polls.js' %}"></script>
{% endblock %}

project/polls/templates/polls/question_detail.html
{% extends "polls/base.html" %}

{% block title %}{{ question.question_text }} - {{ block.super}}{% endblock %}

{% block main %}
{{ block.super }}
<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p>
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}"
      method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input name="choice"
           id="choice-{{ forloop.counter }}"
           type="radio"
           value="{{ choice.id }}" />
    <label for="choice-{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

<a href="{% url 'polls:results' question.id %}">See results</a>
{% endblock %}

project/polls/templates/polls/question_list.html
{% extends "polls/base.html" %}

{% block title %}Home - {{ block.super }}{% endblock %}

{% block main %}
{{ block.super }}
<h1>Questions</h1>

{% if questions %}
<ul>
    {% for question in questions %}
    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

project/polls/templates/polls/question_results.html
{% extends "polls/base.html" %}

{% block title %}Results - {{ block.super }}{% endblock %}

{% block main %}
{{ block.super }}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

project/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static 'css/project.css' %}" rel="stylesheet"/>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% include "header.html" %}

        {% block main %}
            {% block heading %}{% endblock %}
        {% endblock %}

        {% include "footer.html" %}

        <script src="{% static 'js/project.js' %}"></script>
        {% block foot %}
        {% endblock %}
    </body>
</html>

project/templates/footer.html
<footer>
    <p>Copyright &copy; {% now "Y" %}.
        <a href="{% url 'polls:index' %}">Polls App</a>. Some rights reserved
    </p>
</footer>

project/templates/header.html
{% load static %}

<header>
    <a href="{% url 'polls:index' %}">
        <img alt="" src="{% static 'img/project.png' %}" />
    </a>
</header>